services:
  backend:
    build: ./backend
    volumes:
      - backend-data:/app/db
      - ./backend:/app
    ports:
      - "3100:3100"
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:3100"
    

  frontend:
    build: ./clothing-search-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  backend-data:
